### ISSUE TITLE
This is a test issue

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/christina-004#1]
Can you see this @christina-004?

**Comment by uranusjr** [comment]
@christina-004 dup

**Comment by uranusjr** [comment]
test

**Comment by uranusjr** [comment]
test

**Comment by uranusjr** [comment]
@christina-004 クリスティーナ

**Comment by uranusjr** [comment]
@christina-004 クリスティーナ

**Comment by uranusjr** [comment]
a

**Comment by uranusjr** [comment]
est

**Comment by uranusjr** [comment]
a

**Comment by uranusjr** [comment]
b

**Comment by uranusjr** [comment]
c

**Comment by uranusjr** [comment]
d

**Comment by uranusjr** [comment]
e

**Comment by uranusjr** [comment]
f

**Comment by uranusjr** [comment]
g

**Comment by uranusjr** [comment]
h

**Comment by uranusjr** [comment]
i

**Comment by uranusjr** [comment]
j

**Comment by uranusjr** [comment]
k

**Comment by christina-004** [comment]
am i collabo

**Comment by uranusjr** [comment]
test

**Comment by uranusjr** [comment]
2

**Comment by uranusjr** [comment]
3

**Comment by uranusjr** [comment]
4

**Comment by uranusjr** [comment]
5

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by uranusjr** [comment]
@christina-004 dup #2.

**Comment by christina-004** [comment]
Hello there! It looks like your issue is a duplicate to 2.
Kindly refer to its discussion thread for more information.

In there future, please remember to check for all issues in the issue tracker
first, *both open and closed*.

I understand it must be very frustrating to encounter a bug. Our maintainers
feel your pain. They are, however, all volunteers spending free time helping
others. Each duplicate issue cost valuable time to respond, and has negative
impact on constructive work that needs to be done. Please be considerate, and
make the best use of our available resources.

GitHub’s issue search is difficult to search, and we have a lot of issues. You
can try searching `github pipenv issue <keywords>` on Google instead. It
generally finds issues better than GitHub.

I am closing this issue as a duplicate to keep the tracker tidy. Sorry again
for the problem, and thanks so much for taking time to report it. Let’s work
together to make Pipenv better!

🤖🌰🍚💨

**Comment by uranusjr** [comment]
@christina-004 dup #2 #3.

**Comment by christina-004** [comment]
Hello there! It looks like your issue is a duplicate to #2, #3. Kindly refer to their discussion threads for more information.
In there future, please remember to check for all issues in the issue tracker first, *both open and closed*.

I understand it must be very frustrating to encounter a bug. Our maintainers feel your pain. They are, however, all volunteers spending free time helping others. Each duplicate issue cost valuable time to respond, and has negative impact on constructive work that needs to be done. Please be considerate, and make the best use of our available resources.

GitHub’s issue search is difficult to search, and we have a lot of issues. You can try searching `github pipenv issue <keywords>` on Google instead. It generally finds issues better than GitHub.

I am closing this issue as a duplicate to keep the tracker tidy. Sorry again for the problem, and thanks so much for taking time to report it. Let’s work together to make Pipenv better!

🤖🌰🍚💨

**Comment by uranusjr** [comment]
@christina-004 #2 and #3 are duplicates.

**Comment by christina-004** [comment]
Hello there! It looks like your issue is a duplicate to #2, #3. Kindly refer to their discussion threads for more information.

In there future, please remember to check for all issues in the issue tracker first, *both open and closed*.

I understand it must be very frustrating to encounter a bug. Our maintainers feel your pain. They are, however, all volunteers spending free time helping others. Each duplicate issue cost valuable time to respond, and has negative impact on constructive work that needs to be done. Please be considerate, and make the best use of our available resources.

GitHub’s issue search is difficult to search, and we have a lot of issues. You can try searching

    github pipenv issue <keywords>

on Google instead. It generally finds issues better than GitHub.

I am closing this issue as a duplicate to keep the tracker tidy. Sorry again for the problem, and thanks so much for taking time to report it. Let’s work together to make Pipenv better!

🤖🌰🍚💨
